version: '3'
services:
  my-postgres-server:
    image: 'postgres:latest'
    environment:
      - POSTGRES_PASSWORD=${PGPASSWORD}

  my-redis-server:
    image: 'redis:latest'

  my-backend:
    build:
      dockerfile: Dockerfile
      context: ./backend
    volumes:
      - /opt/app/node_modules
      - ./backend:/opt/app
    environment:
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
      - PGUSER=${PGUSER}
      - PGHOST=${PGHOST}
      - PGDATABASE=${PGDATABASE}
      - PGPASSWORD=${PGPASSWORD}
      - PGPORT=${PGPORT}
    ports:
      - '5000:5000'
    stdin_open: true
    tty: true
  
  my-frontend:
    build:
      dockerfile: Dockerfile
      context: ./frontend
    volumes:
      - /opt/app/node_modules
      - ./frontend:/opt/app
    tty: true

  nginx:
    restart: always
    build:
      dockerfile: Dockerfile
      context: ./nginx
    ports:
      - '8080:80'